### ISSUE TITLE
Response code 418 from request

### ISSUE THREAD

**Issue by juiceo** [derhuerst/flightradar24-client#4]
Trying to use this library within a React app, and making calls from the app running on localhost yields a 418 response code. Am I missing some setup step, or why is this happening?

**Comment by derhuerst** [comment]
[HTTP `418` is an April Fool's Day joke](https://www.quora.com/What-is-the-story-behind-HTTP-status-code-418-Im-a-Teapot), so either FlightRadar24 is trolling you or you have a malfunctioning setup.

Can you give me more details in order to reproduce the problem? Maybe all parameters or even a `curl` command (you can get that from the Chrome network inspector)?

**Comment by lappalj4** [comment]
So my usage of the library is exactly as is in the example code in the README.

**Comment by juiceo** [comment]
Hey, thanks for the quick response.

So my code is exactly the same as the example code in README, and when I try the same request url in a browser it works as expected. Request url is: https://data-live.flightradar24.com/zones/fcgi/feed.js?bounds=53%2C52%2C13%2C14&callback=jsonp&faa=1&flarm=1&mlat=1&adsb=1&air=1&gnd=0&vehicles=0&gliders=0

There's a couple of issues that Chrome is complaining about:

* Refused to set unsafe header "user-agent"
* No 'Access-Control-Allow-Origin' header is present. This is likely not related, I am able to fix it a CORS plugin in chrome.

![image](https://user-images.githubusercontent.com/11797156/32496937-9455c28c-c3d3-11e7-8c62-ced289f59922.png)

cURL for the request:

> curl 'https://data-live.flightradar24.com/zones/fcgi/feed.js?bounds=53%2C52%2C13%2C14&callback=jsonp&faa=1&flarm=1&mlat=1&adsb=1&air=1&gnd=0&vehicles=0&gliders=0' -H 'origin: http://localhost:3000' -H 'accept-encoding: gzip, deflate, br' -H 'accept-language: en-GB,en;q=0.8,en-US;q=0.6,fi;q=0.4' -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36' -H 'accept: */*' -H 'referer: http://localhost:3000/' -H 'authority: data-live.flightradar24.com' --compressed

**Comment by derhuerst** [comment]
> when I try the same request url in a browser it works as expected. Request url is: [...]

> cURL for the request: [...]

The `curl` command reproduces the `418` error. It is certainly a weird choice done by FlightRadar24 to return an "I'm a teapot" error on *any* of their public routes.

> No 'Access-Control-Allow-Origin' header is present. This is likely not related, I am able to fix it a CORS plugin in chrome.

~~I will fix this.~~ My code already `fetch`es in CORS mode, so this must be your setup.

**Comment by derhuerst** [comment]
I successfully nailed it down to the `Referer: http://localhost:3000/` header. `Referer: http://foo.bar.horse:3000/` works fine.

**Comment by derhuerst** [comment]
Maybe we can ping someone from @flightradar24 ?

**Comment by juiceo** [comment]
Hmm, so is there a way I can hack the `referer` to an ok value to make it work? For my use case it would just probably be running on localhost and be displayed on a screen

**Comment by derhuerst** [comment]
FlightRadar24 may try to block unauthorised access to their API using this trick. I can set up a CORS proxy that strips the `Referer` at any time though to circumvent it.

I will try to set the `referrer` option of `fetch` to `no-referrer`. But I'm not sure it's supported in every browser.

**Comment by derhuerst** [comment]
Can you confirm it's fixed as of the current `master` (`3eae7ab`)?

**Comment by juiceo** [comment]
hmm, still facing the same issue with `3eae7ab` (0.2.1). Tested on chrome and firefox.

cURL:

> curl 'https://data-live.flightradar24.com/zones/fcgi/feed.js?bounds=53%2C52%2C13%2C14&callback=jsonp&faa=1&flarm=1&mlat=1&adsb=1&air=1&gnd=0&vehicles=0&gliders=0' -H 'origin: http://localhost:3000' -H 'accept-encoding: gzip, deflate, br' -H 'accept-language: en-GB,en;q=0.8,en-US;q=0.6,fi;q=0.4' -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36' -H 'accept: */*' -H 'referer: http://localhost:3000/' -H 'authority: data-live.flightradar24.com' --compressed

**Comment by derhuerst** [comment]
Can you show me the headers being sent? You can see them in the network inspector, when selecting the request.

**Comment by juiceo** [comment]
This is what you're looking for, right?

> :authority:data-live.flightradar24.com
:method:GET
:path:/zones/fcgi/feed.js?bounds=53%2C52%2C13%2C14&callback=jsonp&faa=1&flarm=1&mlat=1&adsb=1&air=1&gnd=0&vehicles=0&gliders=0
:scheme:https
accept:*/*
accept-encoding:gzip, deflate, br
accept-language:en-GB,en;q=0.8,en-US;q=0.6,fi;q=0.4
origin:http://localhost:3000
referer:http://localhost:3000/
user-agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

**Comment by derhuerst** [comment]
Apparently your browser still sent the `Referer` header. Try again with the latest `master` (`faf206b`).

**Comment by derhuerst** [comment]
I assume this has been fixed. Please reopen if the issue still persists.
